version: '3'
services:

  command-app:
    container_name: command-app
    build:
      context: ./
      dockerfile: command.dockerfile
    ports:
      - 3000:3000
    environment:
      MONGO_DB_URI: mongodb://root:password@mongo:27017/inventory?authSource=admin
      RMQ_URI: amqp://root:password@rabbitmq:5672
    links:
      - mongo
      - rabbitmq
    volumes:
      - inventory-app:/command/app

  query-app:
    container_name: query-app
    build:
      context: ./
      dockerfile: query.dockerfile
    ports:
      - 3001:3001
    environment:
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USER: root
      POSTGRES_DB_PASSWORD: password
      POSTGRES_DB_NAME: inventory
      RMQ_URI: amqp://root:password@rabbitmq:5672

    links:
      - mongo
      - rabbitmq
    volumes:
      - inventory-app:/query/app

  proxy-app:
    container_name: proxy-app
    build:
      context: ./
      dockerfile: proxy.dockerfile
    ports:
      - 3002:3002
      - 81:81
    environment:
      RMQ_URI: amqp://root:password@rabbitmq:5672
    links:
      - rabbitmq
    volumes:
      - inventory-app:/command/app

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker-data/data-postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker-data/data-mongo:/data/db

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./docker-data/data-rabbitmq:/var/lib/rabbitmq

volumes:
  data-postgres:
    name: data-postgres
    driver: local
  data-mongo:
    name: data-mongo
    driver: local
  data-rabbitmq:
    name: data-rabbitmq
    driver: local
  inventory-app:
    name: inventory-app
    driver: local
