version: '3.9'
services:
  command-app:
    depends_on:
      - mongo
      - rabbitmq
    image: command-app
    container_name: command-app
    build:
      context: ./
      dockerfile: inventory-command.dockerfile
    restart: always
    ports:
      - "${COMMAND_PORT}:${COMMAND_PORT}"
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_USER: ${MONGO_DB_USER}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_URI: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo:${MONGO_DB_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_DB_AUTH_SOURCE}
      RMQ_URI: amqp://root:password@rabbitmq:5672
    links:
      - mongo
      - rabbitmq
    volumes:
      - inventory-app:/command-app

  query-app:
    depends_on:
      - postgres
      - rabbitmq
    image: query-app
    container_name: query-app
    build:
      context: ./
      dockerfile: inventory-query.dockerfile
    restart: always
    ports:
      - "${QUERY_PORT}:${QUERY_PORT}"
    environment:
      POSTGRES_DB_HOST_QUE: postgres
      POSTGRES_DB_PORT_QUE: ${POSTGRES_DB_PORT_QUE}
      POSTGRES_DB_USER_QUE: ${POSTGRES_DB_USER_QUE}
      POSTGRES_DB_PASSWORD_QUE: ${POSTGRES_DB_PASSWORD_QUE}
      POSTGRES_DB_NAME_QUE: ${POSTGRES_DB_NAME_QUE}
      RMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:${RABBITMQ_DEFAULT_PORT}
      JWT_SECRET: ${JWT_SECRET}
    links:
      - postgres
      - rabbitmq
    volumes:
      - inventory-app:/query-app

  proxy-app:
    depends_on:
      - rabbitmq
    image: proxy-app
    container_name: proxy-app
    build:
      context: ./
      dockerfile: inventory-proxy.dockerfile
    restart: always
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - 81:81
    environment:
      RMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:${RABBITMQ_DEFAULT_PORT}
    links:
      - rabbitmq
    volumes:
      - inventory-app:/proxy-app

  auth-app:
    depends_on:
      - postgres
      - rabbitmq
      - command-app
    image: auth-app
    container_name: auth-app
    build:
      context: ./
      dockerfile: inventory-auth.dockerfile
    restart: always
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      POSTGRES_DB_HOST_AUTH: postgres
      POSTGRES_DB_PORT_AUTH: ${POSTGRES_DB_PORT_AUTH}
      POSTGRES_DB_USER_AUTH: ${POSTGRES_DB_USER_AUTH}
      POSTGRES_DB_PASSWORD_AUTH: ${POSTGRES_DB_PASSWORD_AUTH}
      POSTGRES_DB_NAME_AUTH: ${POSTGRES_DB_NAME_AUTH}
      RMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:${RABBITMQ_DEFAULT_PORT}
      JWT_SECRET: ${JWT_SECRET}
    links:
      - postgres
      - rabbitmq
      - command-app
    volumes:
      - inventory-app:/auth-app

  postgres:
    # image: eduarandres/postgres-app:latest
    image: postgres-app
    container_name: postgres
    build: 
      context: ./
      dockerfile: inventory-postgres.dockerfile
    ports:
      - "${POSTGRES_DB_PORT_QUE}:${POSTGRES_DB_PORT_QUE}"
    restart: always
    command:
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "${POSTGRES_DB_NAME_QUE},${POSTGRES_DB_NAME_AUTH}"
      POSTGRES_MULTIPLE_USERS: "${POSTGRES_DB_USER_QUE},${POSTGRES_DB_USER_AUTH}"
      POSTGRES_MULTIPLE_PASSWORDS: "${POSTGRES_DB_PASSWORD_QUE},${POSTGRES_DB_PASSWORD_AUTH}"
    volumes:
      - data-postgres:/var/lib/postgresql/data

  mongo:
    image: eduarandres/mongo-app:latest
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - data-mongo:/data/db
      - config-mongo:/data/configdb

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_DEFAULT_PORT}:${RABBITMQ_DEFAULT_PORT}"
      - "${RABBITMQ_DEFAULT_MANAGEMENT_PORT}:${RABBITMQ_DEFAULT_MANAGEMENT_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit exchange_definitions '[{\"name\":\"inventory_exchange\"}]'"
    volumes:
      - data-rabbitmq:/var/lib/rabbitmq

volumes:
  data-postgres:
    name: data-postgres
    driver: local
  data-mongo:
    name: data-mongo
    driver: local
  config-mongo:
    name: config-mongo
    driver: local
  data-rabbitmq:
    name: data-rabbitmq
    driver: local
  inventory-app:
    name: inventory-app
    driver: local


# docker-compose --env-file ./environments/.env.dev build
# docker-compose --env-file ./environments/.env.dev up -d