version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker-data/data-postgres:/var/lib/postgresql/data

  zookeeper:
    # image: docker.io/bitnami/zookeeper:latest
    image: docker.io/bitnami/zookeeper:3.8
    # restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - "data-zookeeper:/bitnami"
      # - ./docker-data/data-zookeeper:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    # image: docker.io/bitnami/kafka:latest
    image: docker.io/bitnami/kafka:3.4
    # restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "data-kafka:/bitnami"
      # - ./docker-data/data-kafka:/bitnami
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  # kafka-manager:
  #   image: hlebalbau/kafka-manager:latest
  #   container_name: kafka-manager
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - ZK_HOSTS=zookeeper:2181
  #   depends_on:
  #     - kafka
volumes:
  data-postgres:
    name: data-postgres
    driver: local
  data-mongo:
    name: data-mongo
    driver: local
  data-zookeeper:
    driver: local
  data-kafka:
    driver: local
